name = "sundae/cosponsor"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'sundae/cosponsor'"

[repository]
user = "sundae"
project = "cosponsor"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
